### ISSUE TITLE
review the ras-stac hdf functions

### ISSUE THREAD

**Issue by slawler** [fema-ffrd/rashdf#16]
Let's take a look at the ras-stac functions that are reading from hdf files and decide if we should be implementing them here instead of in the `ras-stac` repo.

**Comment by bates-j** [comment]
@slawler, I took a look at the HDF functionality in `ras-stac` and I like the idea of migrating that over to this repo exclusively just to keep all HDF code in one place if that aligns with the overall vision y'all have in mind?

**Comment by bates-j** [comment]
Sounds good, will do. Issue #17 added.
