### ISSUE TITLE
Create example data

### ISSUE THREAD

**Issue by thwllms** [fema-ffrd/rashdf#2]
We should put some example Plan and/or Geometry HEC-RAS HDF data in `data/` for testing. Ideally this data should be small but complex, and contain the sort of edge cases that we need to test. A single example would be nice. For example:
* Multiple 2D areas
* Mix of 2D and 1D features
* BC lines, breaklines, refinement regions, reference lines, etc.

**Comment by bates-j** [comment]
I extended a geometry within the "Muncie" model downloadable from the HEC-RAS site to include some of the key features for testing. It does not include every single feature available but should give us a good start.

commit -> 90a0e04232d2aa3f832196ba0c965a4ecb6f6934

instructions -> tests/data/ras/README.md
