### ISSUE TITLE
reprojection to WGS84

### ISSUE THREAD

**Issue by bates-j** [fema-ffrd/rashdf#34]
using the `--to-crs` flag to convert `structures` from the "Muncie.go5.hdf" test file to WGS84 and write to a shapefile:
`python ./src/cli.py structures ./tests/data/ras/Muncie.g05.hdf C:/temp/structures.shp --to-crs EPSG:4326`

gives the following error:
RuntimeError: GDAL Error: Coordinates with non-finite values are not allowed. Failed to write record: <fiona.model.Feature object at 0x0000020478593E80>

It seems there is some trouble reprojecting from state plane coordinates directly to WGS84, as this was investigated using other HDF files with different CRS.

**Comment by bates-j** [comment]
investigated fixes related the following post but this did not solve the problem:
[https://gis.stackexchange.com/questions/217939/converting-state-plane-coordinates-to-latitude-longitude](url)

**Comment by thwllms** [comment]
@bates-j does this happen just with `structures` or with other features, too?

**Comment by thwllms** [comment]
@bates-j this seems to work just fine for me:
```
python ./cli.py structures ../tests/data/ras/Muncie.g05.hdf --to-crs EPSG:4326
```

**Comment by bates-j** [comment]
@thwllms can you try this line?
`python ./src/cli.py structures ./tests/data/ras/Muncie.g05.hdf C:/temp/structures.shp --to-crs EPSG:4326`

**Comment by thwllms** [comment]
@bates-j still seems to work for me? Are you on the latest `main`?
![image](https://github.com/fema-ffrd/rashdf/assets/5504267/80647544-d22f-448e-bd96-ea08b2d18dd4)
![image](https://github.com/fema-ffrd/rashdf/assets/5504267/e35fbe34-1d21-4557-a49a-597614d67605)

**Comment by thwllms** [comment]
For the record, I tried downgrading my `pyproj` from 3.6.1 to 3.5.0 (conda on Windows) and I still didn't get the error. Glad it seems to be resolved though.
